baseURL = 'https://oscmartin56.github.io/paginaHugo/'
languageCode = "en-en"
title = 'Web de Óscar'
theme = "hugoblog"

[menu]
  [[menu.main]]
    name = "inicio"
    url = "/inicio/"
    weight = 1

  [[menu.main]]
    name = "Canales TV"
    url = "/canalestv/"
    weight = 3

  [[menu.main]]
    name = "Amigos"
    url = "/amigos/"
    weight = 2

  [[menu.main]]
    name = "Markdown Básico"
    url = "/markdownBasico/"
    weight = 4

  [[menu.main]]
    name = "Markdown Gráfico"
    url = "/markdownGrafico/"
    weight = 5

  [[menu.main]]
    name = "Markdown Extendido"
    url = "/markdownExtendido/"
    weight = 6

  [[menu.main]]
    name = "Java"
    url = "/java/"
    weight = 7


